### PR TITLE
Add documentation on rlm_rest configuration

### PR DESCRIPTION
**Pull request by fredreichbier**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/706%23issuecomment-302045777%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23issuecomment-302855388%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954276%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954502%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954828%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116955113%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r117006760%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r117603632%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r117603633%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r117603654%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23issuecomment-302045777%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%23706%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/7449cf457cec340ff40714499e6caf421880411d%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Aincrease%2A%2A%20coverage%20by%20%600.01%25%60.%5Cn%3E%20The%20diff%20coverage%20is%20%60n/a%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706/graphs/tree.svg%3Ftoken%3D7nHLZki60B%26src%3Dpr%26height%3D150%26width%3D650%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%23706%20%20%20%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20Coverage%20%20%2095.32%25%20%20%2095.34%25%20%20%20%2B0.01%25%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20121%20%20%20%20%20%20121%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2014815%20%20%20%2014815%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20Hits%20%20%20%20%20%20%20%2014123%20%20%20%2014125%20%20%20%20%20%20%20%2B2%20%20%20%20%20%5Cn%2B%20Misses%20%20%20%20%20%20%20%20692%20%20%20%20%20%20690%20%20%20%20%20%20%20-2%5Cn%60%60%60%5Cn%5Cn%5Cn%7C%20%5BImpacted%20Files%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dtree%29%20%7C%20Coverage%20%5Cu0394%20%7C%20%7C%5Cn%7C---%7C---%7C---%7C%5Cn%7C%20%5Bprivacyidea/lib/tokens/u2f.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk%3D%29%20%7C%20%6095.79%25%20%3C0%25%3E%20%28%2B1.68%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B7449cf4...e74f5b3%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/706%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222017-05-17T10%3A05%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/8655789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/codecov-io%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222017-05-20T06%3A53%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%203a168a0aa89b0c37519bdb1fcfa6ef553529bdda%20doc/application_plugins/index.rst%2033%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954276%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22It%20also%20requires%20setting%20up%20freeradius%203%2C%20which%20is%20not%20widely%20shipped%20with%20current%20distributions.%5Cr%5Cn%5Cr%5CnMaybe%20we%20should%20tell%2C%20which%20distris%20ship%20with%20FR3%3F%22%2C%20%22created_at%22%3A%20%222017-05-17T09%3A38%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20doc/application_plugins/index.rst%3AL132-167%22%7D%2C%20%22Pull%203a168a0aa89b0c37519bdb1fcfa6ef553529bdda%20doc/application_plugins/rlm_rest.rst%2013%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116955113%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22So%2017.04%20comes%20with%20FR3%3F%5Cr%5Cn%5Cr%5CnThus%20a%20setup%20might%20look%20like%20this%3A%20privacyIDEA%20on%2016.04%20and%20FR%20on%2017.04%3F%22%2C%20%22created_at%22%3A%20%222017-05-17T09%3A42%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yep%2C%20Ubuntu%2017.04%20ships%20FR%203.0.12%20and%20also%20the%20%60%60freeradius-rest%60%60%20package%3A%20http%3A//packages.ubuntu.com/zesty/freeradius-rest%5Cr%5Cn%5Cr%5CnI%20don%27t%20see%20any%20reason%20why%20this%20setup%20shouldn%27t%20work%20%3A%29%22%2C%20%22created_at%22%3A%20%222017-05-17T13%3A54%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/28243%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222017-05-20T06%3A53%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20doc/application_plugins/rlm_rest.rst%3AL1-66%22%7D%2C%20%22Pull%203a168a0aa89b0c37519bdb1fcfa6ef553529bdda%20doc/application_plugins/rlm_perl.rst%2059%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954828%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22How%20does%20this%20fit%20here%3F%5Cr%5Cn%5Cr%5CnDid%20you%20experience%20any%20issues%20or%20need%20to%20use%20the%20-t%20switch%3F%5Cr%5CnMaybe%20we%20should%20rework%20this%20paragraph%2C%20since%20it%20is%20in%20contrast%20to%20the%20statement%20above%3F%22%2C%20%22created_at%22%3A%20%222017-05-17T09%3A40%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-complete%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222017-05-20T06%3A53%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20doc/application_plugins/rlm_perl.rst%3AL19-65%22%7D%2C%20%22Pull%203a168a0aa89b0c37519bdb1fcfa6ef553529bdda%20doc/application_plugins/rlm_perl.rst%2012%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/706%23discussion_r116954502%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22on%20Ubuntu%2014.04%20LTS%20or%2016.04%20LTS%22%2C%20%22created_at%22%3A%20%222017-05-17T09%3A39%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20will%20add%20this.%22%2C%20%22created_at%22%3A%20%222017-05-20T06%3A55%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20doc/application_plugins/rlm_perl.rst%3AL1-17%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-Pull 3a168a0aa89b0c37519bdb1fcfa6ef553529bdda doc/application_plugins/index.rst 33'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/706#discussion_r116954276'>File: doc/application_plugins/index.rst:L132-167</a></b>
- <a href='https://github.com/cornelinux'></a> It also requires setting up freeradius 3, which is not widely shipped with current distributions.
Maybe we should tell, which distris ship with FR3?
- [ ] <a href='#crh-comment-Pull 3a168a0aa89b0c37519bdb1fcfa6ef553529bdda doc/application_plugins/rlm_perl.rst 12'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/706#discussion_r116954502'>File: doc/application_plugins/rlm_perl.rst:L1-17</a></b>
- <a href='https://github.com/cornelinux'></a> on Ubuntu 14.04 LTS or 16.04 LTS
- <a href='https://github.com/cornelinux'></a> I will add this.
- [x] <a href='#crh-comment-Pull 3a168a0aa89b0c37519bdb1fcfa6ef553529bdda doc/application_plugins/rlm_perl.rst 59'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/706#discussion_r116954828'>File: doc/application_plugins/rlm_perl.rst:L19-65</a></b>
- <a href='https://github.com/cornelinux'></a> How does this fit here?
Did you experience any issues or need to use the -t switch?
Maybe we should rework this paragraph, since it is in contrast to the statement above?
- [x] <a href='#crh-comment-Pull 3a168a0aa89b0c37519bdb1fcfa6ef553529bdda doc/application_plugins/rlm_rest.rst 13'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/706#discussion_r116955113'>File: doc/application_plugins/rlm_rest.rst:L1-66</a></b>
- <a href='https://github.com/cornelinux'></a> So 17.04 comes with FR3?
Thus a setup might look like this: privacyIDEA on 16.04 and FR on 17.04?
- <a href='https://github.com/fredreichbier'></a> Yep, Ubuntu 17.04 ships FR 3.0.12 and also the ``freeradius-rest`` package: http://packages.ubuntu.com/zesty/freeradius-rest
I don't see any reason why this setup shouldn't work :)
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/706#issuecomment-302045777'>General Comment</a></b>
- <a href='https://github.com/codecov-io'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=h1) Report
> Merging [#706](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/7449cf457cec340ff40714499e6caf421880411d?src=pr&el=desc) will **increase** coverage by `0.01%`.
> The diff coverage is `n/a`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=tree)
```diff
@@            Coverage Diff             @@
##           master     #706      +/-   ##
==========================================
+ Coverage   95.32%   95.34%   +0.01%
==========================================
Files         121      121
Lines       14815    14815
==========================================
+ Hits        14123    14125       +2
+ Misses        692      690       -2
```
| [Impacted Files](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [privacyidea/lib/tokens/u2f.py](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk=) | `95.79% <0%> (+1.68%)` | :arrow_up: |
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=footer). Last update [7449cf4...e74f5b3](https://codecov.io/gh/privacyidea/privacyidea/pull/706?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/706?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/706?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/706'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/706'>Refresh</a>.<a href='#crh-update-none'></a>

File: doc/application_plugins/index.rst [hunk 1]
```diff
@@ -132,66 +132,35 @@ to the UBAM token, but this is right now not possible with the WebUI.
...
+Starting with privacyIDEA 2.19, there are two ways to integrate FreeRADIUS:
 
-If you want to run your FreeRADIUS server on another distribution, you
-may download the module at [#rlmPerl]_.
+ * Using a Perl-based privacyIDEA plugin, which is available for FreeRADIUS 2.0.x and above.
+   It supports advanced use cases (such as challenge-response authentication or attribute mapping),
+   but does not implement concurrent handling of multiple requests. Read more about it at :ref:`rlm_perl`.
+ * Using the rlm_rest plugin provided by FreeRADIUS 3.0.x and above. As it implements multithreading,
+   it is suitable for use cases in which high performance is crucial. However, it currently does not support
+   challenge-response or attribute mapping. Read more about it at :ref:`rlm_rest`.
```
Comment (cornelinux) [inline doc/application_plugins/index.rst]: It also requires setting up freeradius 3, which is not widely shipped with current distributions.

Maybe we should tell, which distris ship with FR3?

File: doc/application_plugins/rlm_perl.rst [hunk 2]
```diff
@@ -1,8 +1,16 @@
...
 
-RADIUS plugin configuration
-~~~~~~~~~~~~~~~~~~~~~~~~~~~
+RADIUS plugin
+=============
 
+Installation
+------------
+
+If you want to install the FreeRADIUS Plugin on Ubuntu 14.04 LTS this can be
```
Comment (cornelinux) [inline doc/application_plugins/rlm_perl.rst]: on Ubuntu 14.04 LTS or 16.04 LTS

File: doc/application_plugins/rlm_perl.rst [hunk 3]
```diff
@@ -11,6 +19,46 @@ the following packages to be installed:
...
+While you define the default authenticate type to be ``Perl`` in the
+``users`` file::
+
+   DEFAULT Auth-Type := Perl
+
+.. note:: The privacyIDEA module uses other perl modules that were not thread
+   safe in the
+   past. So in case you are using old perl dependencies and are experiencing
+   thread problems, please start FreeRADIUS with the -t switch.
+   (Everything works fine with Ubuntu 14.04 and Debian 7.)
```
Comment (cornelinux) [inline doc/application_plugins/rlm_perl.rst]: How does this fit here?

Did you experience any issues or need to use the -t switch?
Maybe we should rework this paragraph, since it is in contrast to the statement above?

File: doc/application_plugins/rlm_rest.rst [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+=========================
+
+Starting with version 3.0.x FreeRADIUS is shipped with the ``rlm_rest`` module, which can be used to transform
+RADIUS authentication requests to HTTP requests to a suitable REST endpoint. Starting with version 2.19,
+privacyIDEA implements such an endpoint (``/validate/radiuscheck``, see :ref:`rest_validate`).
+
+Please note that the endpoint currently does not implement all features of the :ref:`rlm_perl` such as
+challenge-response authentication and attribute mapping.
+
+On Ubuntu 17.04, FreeRADIUS and ``rlm_rest`` can be installed as follows::
```
Comment (cornelinux) [inline doc/application_plugins/rlm_rest.rst]: So 17.04 comes with FR3?

Thus a setup might look like this: privacyIDEA on 16.04 and FR on 17.04?

Comment (fredreichbier) [inline doc/application_plugins/rlm_rest.rst]: Yep, Ubuntu 17.04 ships FR 3.0.12 and also the ``freeradius-rest`` package: http://packages.ubuntu.com/zesty/freeradius-rest

**Comment by cornelinux** [comment]
:+1:<a href='#crh-update-none'></a>

File: doc/application_plugins/rlm_rest.rst (hunk 4 above)
Comment (cornelinux) [inline doc/application_plugins/rlm_rest.rst]: :+1:<a href='#crh-update-none'></a>

File: doc/application_plugins/rlm_perl.rst (hunk 3 above)
Comment (cornelinux) [inline doc/application_plugins/rlm_perl.rst]: :+1:<a href='#crh-update-complete'></a>

File: doc/application_plugins/rlm_perl.rst (hunk 2 above)
Comment (cornelinux) [inline doc/application_plugins/rlm_perl.rst]: I will add this.
