### ISSUE TITLE
Check audit log rotation

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#624]
Rotating the audit log fails with an error.

In one installation it was reported, that rotating the audit log failes with an exception.
On another installation that looked the same, the error was not observed.

-> investigate

<pre>
Cleaning up with high: 400, low: 250. mysql://pi:pi@localhost/pi
The log audit log has 492 entries, the last one is 493
More than 400 entries, deleting...
Deleting entries smaller than 243
Traceback (most recent call last):
  File "/usr/bin/pi-manage", line 622, in <module>
    manager.run()
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 402, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/bin/pi-manage", line 403, in rotate_audit
    session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 361, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 162, in session_signal_before_commit
    d = session._model_changes
AttributeError: 'Session' object has no attribute '_model_changes'
</pre>

# Versions

privacyIDEA: 2.17
Installation method: Ubuntu Xenial Launchapd
OS: Ubuntun 16.04
Webserver: Apache
Tokendatabase: MySQL

# What did you try to do?

Rotate the audit log

# What outcome did you expect?

Audit log should be rotated, no error.

# What outcome did you experience?

An exception was raised.
The audit log was not rotated.

**Comment by cornelinux** [comment]
Rotation works fine in 2.17 and 2.18dev.
pi-manage was enhanced.
